FROM ubuntu:latest

WORKDIR /opt/

COPY . /opt/

RUN rm -f src/main/resources/application.properties
RUN cp -rf application.properties src/main/resources/application.properties
RUN apt update -y && apt install openjdk-21-jdk -y
RUN apt update -y && apt install maven -y
RUN mvn clean package -DskipTests


EXPOSE 8081

CMD ["java","-jar","target/student-registration-backend-0.0.1-SNAPSHOT.jar","&"]
